# Copyright (c) 2023-2026. Cloud Software Group, Inc.
# This file is subject to the license terms contained
# in the license file that is distributed with this file.

#---------------------------------------------------------------------------------------------
# install Azure CLI
# https://github.com/Azure/azure-cli/issues/19591
# AZURE_CLI_VERSION=2.74.0

FROM python:3.12.11-alpine3.22 AS builder-azure
ARG AZURE_CLI_VERSION=2.74.0
WORKDIR /azure
RUN apk add --no-cache --update python3 py3-pip && \
    apk add --no-cache --update --virtual=build gcc musl-dev python3-dev libffi-dev openssl-dev cargo make && \
    python -m venv .venv && .venv/bin/pip install -U pip && \
    .venv/bin/pip --no-cache-dir install azure-cli==${AZURE_CLI_VERSION} && \
    find / -name __pycache__ | xargs -r rm -rf
#---------------------------------------------------------------------------------------------
# actual run time image
# KUBECTL_VERSION=1.33.1
# OC_VERSION=4.18.17

FROM alpine:3.22
ARG KUBECTL_VERSION=1.33.1
ARG OC_VERSION=4.18.17
ARG TARGETOS=linux
ARG TARGETARCH=amd64

# base packages
RUN apk add --no-cache --upgrade \
    coreutils \
    util-linux \
    gettext \
    bash \
    gcompat \
    curl \
    wget \
    jq \
    openssl \
    git \
    python3 \
    yq \
    helm && rm -rf /var/cache/apk/*

# COPY azure cli to BASE_IMAGE
COPY --from=builder-azure /azure /azure
RUN ln -sf /usr/bin/python3 /usr/local/bin/python && ln -sf /azure/.venv/bin/az /usr/local/bin/az

RUN echo "KUBECTL_VERSION=${KUBECTL_VERSION}" && \
    curl -sLO https://dl.k8s.io/release/v${KUBECTL_VERSION}/bin/${TARGETOS}/${TARGETARCH}/kubectl && \
    chmod +x ./kubectl && mv -f ./kubectl /usr/local/bin/kubectl && \
    kubectl version --client=true

# OpenShift CLI
RUN echo "OC_VERSION=${OC_VERSION}" && \
    curl --silent --location "https://mirror.openshift.com/pub/openshift-v4/clients/ocp/${OC_VERSION}/openshift-client-${TARGETOS}-${OC_VERSION}.tar.gz" | tar xz -C /tmp; \
    chmod +x /tmp/oc && mv -f /tmp/oc /usr/local/bin/oc && \
    oc version --client=true

CMD ["/bin/bash"]